 const ApiEvent = {
        INCENTIVIZED_AD_SHOW: "INCENTIVIZED_AD_SHOW",
        INCENTIVIZED_AD_CHECK_STATUS: "INCENTIVIZED_AD_CHECK_STATUS",
        INCENTIVIZED_AD_STATUS: "INCENTIVIZED_AD_STATUS",
        INCENTIVIZED_AD_COMPLETED: "INCENTIVIZED_AD_COMPLETED",
        INCENTIVIZED_AD_ABANDONED: "INCENTIVIZED_AD_ABANDONED"
    };

    export default ApiEvent;