const GameUiEvent = {

        SHOW_FACTORY: "SHOW_FACTORY",
        SHOW_FACTORIES: "SHOW_FACTORIES",
        SHOW_RESEARCH: "SHOW_RESEARCH",
        SHOW_UPGRADES: "SHOW_UPGRADES",
        SHOW_ACHIEVEMENTS: "SHOW_ACHIEVEMENTS",
        SHOW_HELP: "SHOW_HELP",
        SHOW_STATISTICS: "SHOW_STATISTICS",
        SHOW_PURCHASES: "SHOW_PURCHASES",
        SHOW_SETTINGS: "SHOW_SETTINGS",
        SHOW_TIME_TRAVEL: "SHOW_TIME_TRAVEL",
    GAME_TICK: "GAME_TICK",
    MONEY_UPDATED: "MONEY_UPDATED",
    RESEARCH_POINTS_UPDATED: "RESEARCH_POINTS_UPDATED",
    ACHIEVEMENT_RECEIVED: "ACHIEVEMENT_RECEIVED",
    TOGGLE_TICKS: "TOGGLE_TICKS",
    TICKS_STOPPED: "TICKS_STOPPED",
    TICKS_STARTED: "TICKS_STARTED",
    BONUS_TICKS_UPDATED: "BONUS_TICKS_UPDATED",
    TIME_TRAVEL_TICKETS_UPDATED: "TIME_TRAVEL_TICKETS_UPDATED",
    FOCUS: "FOCUS",
    BLUR: "BLUR",
    RESEARCH_BOUGHT: "RESEARCH_BOUGHT",
    BACKGROUND_MODE_ACTIVATED: "BACKGROUND_MODE_ACTIVATED",
    BACKGROUND_MODE_DISABLED: "BACKGROUND_MODE_DISABLED",
    PREMIUM_STATUS_CHANGED: "PREMIUM_STATUS_CHANGED"
    };

    export default GameUiEvent;