const GameUiEvent = {

        SHOW_FACTORY: "SHOW_FACTORY",
        SHOW_FACTORIES: "SHOW_FACTORIES",
        SHOW_RESEARCH: "SHOW_RESEARCH",
        SHOW_UPGRADES: "SHOW_UPGRADES",
        SHOW_ACHIEVEMENTS: "SHOW_ACHIEVEMENTS",
        SHOW_HELP: "SHOW_HELP",
        SHOW_STATISTICS: "SHOW_STATISTICS",
        SHOW_PURCHASES: "SHOW_PURCHASES",
        SHOW_SETTINGS: "SHOW_SETTINGS",
        SHOW_TIME_TRAVEL: "SHOW_TIME_TRAVEL"
    };

    export default GameUiEvent;