// GlobalUiEvent.js
const GlobalUiEvent = {
    KEY_PRESS: "KEY_PRESS",
    FOCUS: "FOCUS",
    BLUR: "BLUR",
    SHOW_MAIN_GAME: "SHOW_MAIN_GAME",
    SHOW_MISSIONS: "SHOW_MISSIONS",
    SHOW_MISSION: "SHOW_MISSION",
    SHOW_SETTINGS: "SHOW_SETTINGS",
    SHOW_TIME_TRAVEL: "SHOW_TIME_TRAVEL",
    SHOW_PURCHASES: "SHOW_PURCHASES",
    SHOW_HELP: "SHOW_HELP",
    OPEN_SCREENSHOT_VIEW: "SHOW_SCREENSHOT_VIEW"

  };
  
  export default GlobalUiEvent;